name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python deps (headless only)
        run: |
          python -m pip install --upgrade pip
          pip install psutil pytest
          pip install -e .

      - name: Run tests
        run: pytest -v
